name: Static Site Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy Files
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          source: "./"
          target: "/var/www/html/test/mandar-portfolio"
          overwrite: true
          strip_components: 1
